### ISSUE TITLE
Nested routes are ignored

### ISSUE THREAD

**Issue by andrewGuscha** [oklas/react-breadcrumbs-dynamic#12]
This bug appeared in version 1.0.11
Bug Demo: https://andrewguscha.github.io/react-breadcrumbs-bug-demo/index.html#/
Bug Source: https://github.com/andrewGuscha/react-breadcrumbs-bug-demo/blob/master/src/App.js

1. Breadcrumbs renders correctly with this steps: Home->About->Components
2. Breadcrumbs renders incorrectly with this steps: Home->Topics->Components 
With this steps, BreadcrumbItem 'Topics' didn't appear.

**Comment by bartekczyz** [comment]
Same issue here

**Comment by oklas** [comment]
This behaviour was before 1.0.11 too but it was hidden by additional update and render stages. No such stages now performed since that is optimized. So this behaviour is surfaced.

This good use case show it up. I added this use case to tests. However it is not reproduced the problem in jest testing environment. Because it is reproduced only in browser. Fixed since 1.0.13.

Thank you. Feel free to reopen or create new.
