### ISSUE TITLE
Semantic Versioning 

### ISSUE THREAD

**Issue by zmeecer** [oklas/react-breadcrumbs-dynamic#13]
That's an awesome package, really
But, could you use semantic versioning cuz your last versions have broken my builds
Thanks!

**Comment by oklas** [comment]
Thank you! I'd like to make it better.
About versioning, may be I missed to change minor instead of patch but system is changed without adding new functionality. Also there is no public API functionality is marked as deprecated. May be I missed something. Changes must not to get builds broken. What is exactly error may be some another problem? I will be happy to solve.

**Comment by zmeecer** [comment]
Oh, sorry, I've checked the issue again

That's my fault. It was silly typo with comma inside of BreadcrumbsProvider and, as result, two elements inside ThroughProvider (there must be only one). 

By the way, what's difference between BreadcrumbsProvider import and import ThroughProvider from a separate package? 

Tell me if I can help you somehow with this package

**Comment by oklas** [comment]
Sure who never climbed never fell. A typos is more wonderful when it is compiled and pass tests.

ThroughProvider is replacement of BreadcrumbsProvider and currently it implemented as synonym. It make same things more effective and allows to work another libraries like this. Must be only one such object in tree. However there is no problem if it more than one to work - may be react itself will warn or not. Only one will be worked, and others will be ballast.

 I am interesting now what is the diversity of use cases react-through at all. It seems most usefull to create libraries however and in application too.
